version: "2.1"
services:
  swag:
    build: .
    container_name: paintai
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=paintai.groupmind.co.uk
      - VALIDATION=http
    volumes:
      - ./config:/config
      - ../www:/config/www
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
